# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:
  REPO_DIR: scikit-image
  WHEELHOUSE_UPLOADER_USERNAME: appveyor-worker
  # https://www.appveyor.com/docs/build-configuration/#secure-variables
  WHEELHOUSE_UPLOADER_SECRET:
    secure: TBD
  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64

matrix:
  fast_finish: true

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"

  # Get stdint headers needed by tifffile.c.
  - "curl https://raw.githubusercontent.com/chemeris/msinttypes/master/inttypes.h -o skimage/external/tifffile/inttypes.h"
  - "curl https://raw.githubusercontent.com/chemeris/msinttypes/master/stdint.h -o skimage/external/tifffile/stdint.h"

  # Install the build and runtime dependencies of the project.
  # The --pre flag is necessary to grab a SciPy wheel, which is in
  # pre-release at the time of writing (03-10-2017)
  - cd %REPO_DIR%
  - pip install --pre -r requirements.txt
  - pip install -r requirements/build.txt
  - python setup.py bdist_wheel bdist_wininst
  - ps: "ls dist"

  # Install the generated wheel package to test it
  - "pip install --pre --no-index --find-links dist/ scikit-image"

# Not a .NET project, we build scikit-image in the install step instead
build: false

#test_script:
  # Tests have already been run in main repo

on_success:
  - pip install wheelhouse-uploader
  - python -m wheelhouse_uploader upload 
      --local-folder %REPO_DIR%\\dist
      --no-update-index
      wheels

cache:
  # Avoid re-downloading large packages
  - '%APPDATA%\pip\Cache'
